version: '3.8'
services:
  backend:
    build:
      context: ./aqua-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - db_data:/data/db
  client:
    build:
      context: ./aqua-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  db_data: {}
